In [2]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
print(arr)

[1 2 3 4 5]


In [9]:
array = np.array('A')
print(array.ndim)

0


In [10]:
array = np.array(['a','b','c','d'])
print(array.ndim)

1


In [32]:
# create a 2D array
array = np.array([['a', 'b', 'c', 'd'],
                  ['a', 'b', 'c', 'd']])

# print number of dimensions
print(array.ndim)


2


In [33]:
array_1 = np.array([1,2,3,4,5,6])
array_2 = np.array([7,8,9,10,11,12])

my_array = array_1 + array_2
print(my_array)

[ 8 10 12 14 16 18]


In [42]:
array_1 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])
print(array_1[0:,1:2])

[[ 2]
 [ 6]
 [10]]


In [44]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  7


In [49]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

print("3rd element on 2nd row is:",arr[1,2])

3rd element on 2nd row is: 7


In [57]:
#Access the third element of the second array of the first array:
arr = np.array([[[1, 2, 3], [4, 5, 6]], 
                [[7, 8, 9], [10, 11, 12]]])

print("accessing third element of the second array of the first array", arr[0,1,2])

accessing third element of the second array of the first array 6


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [2]:
#Slice elements from index 4 to the end of the array
arr = np.array([1,2,3,4,5,6,7])

print(arr[4:])

[5 6 7]


In [3]:
#Slice elements from the beginning to index 4 (not included):
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [4]:
#Slice from the index 3 from the end to index 1 from the end:
arr = np.array([1,2,3,4,5,6,7])
print(arr[:-1])

[1 2 3 4 5 6]


In [14]:
#Return every other element from index 1 to index 5:
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:6:1])

[3 4 5 6]


In [15]:
#From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [20]:
#From both elements, return index 2:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2,2])

[3 8]


In [26]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [27]:
#Everything from (including) the second item to (not including) the fifth item.
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[1:4])

[15 20 25]


In [31]:
#Every other item from (including) the second item to (not including) the fifth item.
#Tip: use the step syntax.
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[::2])

[10 20 30 40]


In [4]:
# Arthimetic
array = np.array([1,2,3,4])

print(np.sqrt(array))


[1.         1.41421356 1.73205081 2.        ]


In [9]:
array = np.array([1,2,3,4])

sqr_root = (np.sqrt(array))
print(np.round(sqr_root))

[1. 1. 2. 2.]


In [14]:
#arthimetic operations
array_1 = np.array([1,2,3,4,5])
array_2 = np.array([6,7,8,9,10])

print(np.array(array_1 + array_2))
print(np.array(array_1 * array_2))
print(np.array(array_1 / array_2))
print(np.array(array_1 - array_2))

[ 7  9 11 13 15]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[-5 -5 -5 -5 -5]


In [19]:
#comparision operators
score = np.array([10,100,4,25,77,88,90])
print(score >=0)

[ True  True  True  True  True  True  True]


In [20]:
#shape
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [24]:
arr = np.array([1, 2, 3, 4], ndmin=2)

print(arr)
print('shape of array :', arr.shape)

[[1 2 3 4]]
shape of array : (1, 4)


In [23]:
array = np.array([1,2,3,4,5,6],ndmin = 3)
print(array)
print("shape:",array.shape)

[[[1 2 3 4 5 6]]]
shape: (1, 1, 6)


In [33]:
#reshaped
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
print(arr.shape)
print(reshaped)

(6,)
[[1 2 3]
 [4 5 6]]


In [35]:
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,-1)
print(reshaped)

[[1 2 3]
 [4 5 6]]
